version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@6.8.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: false
          dockerfile: Dockerfile
          path: .circleci/images
          profile-name: ContainerRegistryServiceUser
          region: AWS_REGION_ENV_VAR_NAME
          repo: dfd-dev
          tag: '20200505v5'
